# Generated by Django 5.1.7 on 2025-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0003_customuser_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
