# Generated by Django 5.1.7 on 2025-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
