# Generated by Django 5.1.7 on 2025-03-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
