# Generated by Django 5.1.7 on 2025-03-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0005_manifestuser_groups_manifestuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='manifestuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ManifestLetter',
        ),
        migrations.DeleteModel(
            name='ManifestUser',
        ),
    ]
