# Generated by Django 5.1.7 on 2025-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0006_remove_customuser_dob_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
    ]
