# Generated by Django 5.1.7 on 2025-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestletter',
            name='user',
            field=models.TextField(),
        ),
    ]
