# Generated by Django 5.1.7 on 2025-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0007_alter_manifestletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=25),
        ),
    ]
