# Generated by Django 5.1.7 on 2025-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifestapp', '0008_alter_manifestletter_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManifestUser',
        ),
    ]
